const products = [
  {
    _id: '1',
    name: 'Daryl Dixon',
    series: 'The Walking Dead',
    image_front: '/pop-images/daryl_front.png',
    image_back: '/pop-images/daryl_back.png',
    description: 'Funko Pop Vinyl Figure ',
    brand: 'Pop Vinyl',
    category: 'Toy',
    price: 4.99,
    countInStock: 1,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'The Governor',
    series: 'The Walking Dead',
    image_front: '/pop-images/governor_front.png',
    image_back: '/pop-images/governor_back.png',
    description: 'Funko Pop Vinyl Figure ',
    brand: 'Pop Vinyl',
    category: 'Toy',
    price: 4.99,
    countInStock: 1,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Michonne',
    series: 'The Walking Dead',
    image_front: '/pop-images/michonne_front.png',
    image_back: '/pop-images/michonne_back.png',
    description: 'Funko Pop Vinyl Figure ',
    brand: 'Pop Vinyl',
    category: 'Toy',
    price: 4.99,
    countInStock: 1,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Rick Grimes',
    series: 'The Walking Dead',
    image_front: '/pop-images/rick_front.png',
    image_back: '/pop-images/rick_back.png',
    description: 'Funko Pop Vinyl Figure ',
    brand: 'Pop Vinyl',
    category: 'Toy',
    price: 4.99,
    countInStock: 1,
    rating: 5,
    numReviews: 12,
  },
];

export default products;
